version: "3"

services:
  calculator_app:
    build: .
    container_name: calculator_app
    ports:
      - "5006:5000"  # Flask app accessible on port 5006
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "81:81"  # Nginx listens on port 81
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - calculator_app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
